services:
  framextract:
    build:
      context: .
      dockerfile: Dockerfile
    image: framextract:latest
    container_name: framextractor
    environment:
      - JUPYTER_ENABLE_LAB=yes
    stdin_open: true
    tty: true
    ports:
      - 8888:8888
    volumes:
      # Application directory
      - .:/home
      # Image directory
      - .:/images
      # Video directory
      - .:/videos
      # Data directory
      - .:/data
    # entrypoint: python3 frameXtract.py
    # command: python3 frameXtract.py -h
